# Generated by Django 5.1.4 on 2025-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtentiCredenzialiCalcolatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
