# Generated by Django 5.1.4 on 2025-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcolatore', '0002_tabellapazienti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
