# Generated by Django 5.1.4 on 2025-02-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calcolatore', '0003_alter_tabellapazienti_codice_fiscale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='cap',
        ),
    ]
