# Generated by Django 5.1.4 on 2025-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
