# Generated by Django 5.0.3 on 2024-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utentiregistraticredenziali',
            name='password',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
