# Generated by Django 5.1.4 on 2025-05-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0002_delete_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('contenuto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
