# Generated by Django 5.1.4 on 2025-04-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0002_utentiregistraticredenziali_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utentiregistraticredenziali',
            name='cookie',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
