# Generated by Django 5.0.3 on 2024-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0002_utentiregistraticredenziali_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utentiregistraticredenziali',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
