# Generated by Django 5.1.4 on 2025-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0003_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tipologia_visita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
