# Generated by Django 5.1.4 on 2025-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0003_alter_utentiregistraticredenziali_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='google_token_expiry',
        ),
        migrations.AlterField(
            model_name='utentiregistraticredenziali',
            name='cookie',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
