# Generated by Django 5.0.3 on 2024-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0003_utentiregistraticredenziali_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabellaPazienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('chronological_age', models.IntegerField(blank=True, null=True)),
                ('obri_index', models.FloatField(blank=True, null=True)),
                ('d_roms', models.FloatField(blank=True, null=True)),
                ('aa_epa', models.FloatField(blank=True, null=True)),
                ('aa_dha', models.FloatField(blank=True, null=True)),
                ('homa_test', models.FloatField(blank=True, null=True)),
                ('cardiovascular_risk', models.FloatField(blank=True, null=True)),
                ('osi', models.FloatField(blank=True, null=True)),
                ('pat', models.FloatField(blank=True, null=True)),
                ('wbc', models.FloatField(blank=True, null=True)),
                ('baso', models.FloatField(blank=True, null=True)),
                ('eosi', models.IntegerField(blank=True, null=True)),
                ('lymph', models.FloatField(blank=True, null=True)),
                ('mono', models.FloatField(blank=True, null=True)),
                ('neut', models.FloatField(blank=True, null=True)),
                ('rbc', models.FloatField(blank=True, null=True)),
                ('hct', models.FloatField(blank=True, null=True)),
                ('hgb', models.FloatField(blank=True, null=True)),
                ('mch', models.FloatField(blank=True, null=True)),
                ('mchc', models.FloatField(blank=True, null=True)),
                ('mcv', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('ferritin', models.FloatField(blank=True, null=True)),
                ('albumin', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('bilirubin', models.FloatField(blank=True, null=True)),
                ('uric_acid', models.FloatField(blank=True, null=True)),
                ('biological_age', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
