# Generated by Django 5.1.4 on 2025-06-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0004_alter_appointment_tipologia_visita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='voce_prezzario',
            new_name='visita',
        ),
        migrations.AddField(
            model_name='appointment',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
