# Generated by Django 5.1.4 on 2025-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0004_alter_tabellapazienti_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='rh_factor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
