# Generated by Django 5.0.3 on 2024-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0005_archivioreferti_delete_refertabelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivioreferti',
            name='biological_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='chronological_age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
