# Generated by Django 5.2.2 on 2025-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0005_rename_voce_prezzario_appointment_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='note_patologie',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
