# Generated by Django 5.1.4 on 2025-04-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0005_alter_tabellapazienti_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esamevisita',
            name='visita',
        ),
        migrations.CreateModel(
            name='PrescrizioniEsami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(auto_now_add=True)),
                ('esami_prescritti', models.TextField(blank=True, null=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite', to='BioVitalAge.tabellapazienti')),
            ],
        ),
        migrations.DeleteModel(
            name='ElencoVisitePaziente',
        ),
        migrations.DeleteModel(
            name='EsameVisita',
        ),
    ]
