# Generated by Django 5.1.4 on 2025-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0005_utentiregistraticredenziali_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='user',
        ),
    ]
