# Generated by Django 5.0.3 on 2024-12-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0006_archivioreferti_biological_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivioreferti',
            name='biological_age',
        ),
        migrations.RemoveField(
            model_name='archivioreferti',
            name='chronological_age',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='aa_dha',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='aa_epa',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='albumin',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='baso',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='bilirubin',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='biological_age',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='cardiovascular_risk',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='chronological_age',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='creatinine',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='d_roms',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='eosi',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='ferritin',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='hct',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='hgb',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='homa_test',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='lymph',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='mch',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='mchc',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='mcv',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='mono',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='neut',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='obri_index',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='osi',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='rbc',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='uric_acid',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='wbc',
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='dottore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pazienti', to='BioVitalAge.utentiregistraticredenziali'),
        ),
        migrations.CreateModel(
            name='DatiEstesiReferti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronological_age', models.IntegerField(blank=True, null=True)),
                ('obri_index', models.FloatField(blank=True, null=True)),
                ('d_roms', models.FloatField(blank=True, null=True)),
                ('aa_epa', models.FloatField(blank=True, null=True)),
                ('aa_dha', models.FloatField(blank=True, null=True)),
                ('homa_test', models.FloatField(blank=True, null=True)),
                ('cardiovascular_risk', models.FloatField(blank=True, null=True)),
                ('osi', models.FloatField(blank=True, null=True)),
                ('pat', models.FloatField(blank=True, null=True)),
                ('wbc', models.FloatField(blank=True, null=True)),
                ('baso', models.FloatField(blank=True, null=True)),
                ('eosi', models.IntegerField(blank=True, null=True)),
                ('lymph', models.FloatField(blank=True, null=True)),
                ('mono', models.FloatField(blank=True, null=True)),
                ('neut', models.FloatField(blank=True, null=True)),
                ('rbc', models.FloatField(blank=True, null=True)),
                ('hct', models.FloatField(blank=True, null=True)),
                ('hgb', models.FloatField(blank=True, null=True)),
                ('mch', models.FloatField(blank=True, null=True)),
                ('mchc', models.FloatField(blank=True, null=True)),
                ('mcv', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('ferritin', models.FloatField(blank=True, null=True)),
                ('albumin', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('bilirubin', models.FloatField(blank=True, null=True)),
                ('uric_acid', models.FloatField(blank=True, null=True)),
                ('biological_age', models.FloatField(blank=True, null=True)),
                ('referto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dati_estesi', to='BioVitalAge.archivioreferti')),
            ],
        ),
    ]
