# Generated by Django 5.2.2 on 2025-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0006_tabellapazienti_note_patologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='note_patologie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
