# Generated by Django 5.1.4 on 2025-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0006_remove_esamevisita_visita_prescrizioniesami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utentiregistraticredenziali',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
