# Generated by Django 5.1.4 on 2025-04-17 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0007_alter_utentiregistraticredenziali_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerapiaDomiciliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=200)),
                ('num_assunzioni', models.PositiveSmallIntegerField()),
                ('orari', models.JSONField(blank=True, null=True)),
                ('data_inizio', models.DateField()),
                ('in_corso', models.BooleanField(default=False)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TerapiaStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IV', 'IV therapy')], max_length=10)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateField()),
                ('in_corso', models.BooleanField(default=False)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
