# Generated by Django 5.1.5 on 2025-04-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0007_utentiregistraticredenziali_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='user',
        ),
    ]
