# Generated by Django 5.2.2 on 2025-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0007_alter_tabellapazienti_note_patologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='isSecretary',
        ),
        migrations.AddField(
            model_name='utentiregistraticredenziali',
            name='role',
            field=models.CharField(choices=[('doctor', 'Medico'), ('secretary', 'Segreteria'), ('admin', 'Admin')], default='doctor', max_length=20),
        ),
    ]
