# Generated by Django 5.1.4 on 2025-04-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0008_terapiadomiciliare_terapiastudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapiastudio',
            name='persona',
        ),
        migrations.DeleteModel(
            name='TerapiaDomiciliare',
        ),
        migrations.DeleteModel(
            name='TerapiaStudio',
        ),
    ]
