# Generated by Django 5.0.3 on 2024-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0008_utentiregistraticredenziali_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='utentiregistraticredenziali',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utentiregistraticredenziali',
            name='password',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
