# Generated by Django 5.1.4 on 2025-04-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0009_remove_terapiastudio_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerapiaDomiciliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=255)),
                ('assunzioni', models.IntegerField()),
                ('orari', models.JSONField()),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapie_domiciliari', to='BioVitalAge.tabellapazienti')),
            ],
        ),
        migrations.CreateModel(
            name='TerapiaInStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapie_studio', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
