# Generated by Django 5.1.5 on 2025-04-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0009_utentiregistraticredenziali_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utentiregistraticredenziali',
            name='user',
        ),
    ]
