# Generated by Django 5.0.3 on 2024-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0009_remove_utentiregistraticredenziali_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivioreferti',
            name='data_referto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
