# Generated by Django 5.1.4 on 2025-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0010_terapiadomiciliare_terapiainstudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapiadomiciliare',
            name='data_inizio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='terapiadomiciliare',
            name='orari',
            field=models.JSONField(null=True),
        ),
    ]
