# Generated by Django 5.0.3 on 2024-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0010_alter_archivioreferti_data_referto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datiestesireferti',
            name='biological_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
