# Generated by Django 5.1.4 on 2025-04-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0010_terapiadomiciliare_terapiainstudio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatiEstesiRefertiTest',
            new_name='DatiEstesiRefertiCapacitaVitale',
        ),
        migrations.RenameModel(
            old_name='DatiEstesiReferti',
            new_name='DatiEstesiRefertiEtaBiologica',
        ),
        migrations.RenameModel(
            old_name='ArchivioRefertiTest',
            new_name='RefertiCapacitaVitale',
        ),
        migrations.RenameModel(
            old_name='ArchivioReferti',
            new_name='RefertiEtaBiologica',
        ),
    ]
