# Generated by Django 5.1.5 on 2025-04-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0011_alter_terapiadomiciliare_data_inizio_and_more'),
        ('BioVitalAge', '0011_rename_datiestesireferti'),
    ]

    operations = [
    ]
