# Generated by Django 5.0.3 on 2024-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0011_alter_datiestesireferti_biological_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='aa_dha',
            new_name='O3_index',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='aa_epa',
            new_name='aa_epa_quotient',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='cardiovascular_risk',
            new_name='azotemia',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='homa_test',
            new_name='fa_saturated',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='obri_index',
            new_name='o3fatty_acids',
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='o6fatty_acids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='o6o3_fatty_acids_quotient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='o9o7fatty_acids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='s_u_fatty_acids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
