# Generated by Django 5.1.5 on 2025-04-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0012_merge_20250430_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('data_diagnosi', models.DateField()),
                ('stato', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('gravita', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosi', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
