# Generated by Django 5.0.3 on 2024-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0012_rename_aa_dha_datiestesireferti_o3_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datiestesireferti',
            name='chronological_age',
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='chronological_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
