# Generated by Django 5.1.4 on 2025-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0013_diagnosi'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosi',
            name='risolta',
            field=models.BooleanField(default=False),
        ),
    ]
