# Generated by Django 5.0.3 on 2024-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0013_remove_datiestesireferti_chronological_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
