# Generated by Django 5.0.3 on 2024-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0014_alter_tabellapazienti_codice_fiscale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='albumin',
            new_name='a_1',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='bilirubin',
            new_name='a_1_dI',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='glucose',
            new_name='a_2',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='protein',
            new_name='a_2_dI',
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='a_photo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ag_rap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='albumin_dI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='albumin_ele',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='albuminemia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_1_dI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_2_dI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_2_spike',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='b_2_spike_m1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='baso_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='bilirubin_ex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='blood_ex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='direct_bili',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='eosi_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='fe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='g_gt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gamma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gamma_dI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='glicemy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='glucose_ex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='got',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gpt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hdl_chol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='homa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='homocysteine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='idirect_bili',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ketones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ldl_chol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='leuc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='lymph_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='mono_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='mpv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='neut_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='pcr_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='pdw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='plcr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='plt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='proteins_ex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='rdwcv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='rdwsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='s_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tot_bili',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tot_chol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tot_prot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tot_prot_ele',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='transferrin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='trigl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='uro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ves',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datiestesireferti',
            name='eosi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
