# Generated by Django 5.1.4 on 2025-05-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0014_diagnosi_risolta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllegatiLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='laboratorio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati_laboratorio', to='BioVitalAge.tabellapazienti')),
            ],
        ),
        migrations.CreateModel(
            name='AllegatiStrumentale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='strumentale/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati_strumentale', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
