# Generated by Django 5.1.4 on 2025-05-07 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0015_allegatilaboratorio_allegatistrumentale'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegatilaboratorio',
            name='data_referto',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='allegatistrumentale',
            name='data_referto',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
