# Generated by Django 5.1.4 on 2025-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0015_rename_albumin_datiestesireferti_a_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivioreferti',
            name='alcol',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='alcol_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='alcol_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='attivita_sedentaria',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='bmi',
            field=models.FloatField(help_text='Body Mass Index', null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='bmi_detection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='data_alcol',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='girth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='girth_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='girth_value',
            field=models.FloatField(help_text='Girth value in cm', null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='height',
            field=models.FloatField(help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='livello_sedentarieta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='reduced_intake',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='sedentarieta_nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='smoke',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='smoke_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='sport',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='sport_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='sport_livello',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivioreferti',
            name='weight',
            field=models.FloatField(help_text='Weight in kg', null=True),
        ),
    ]
