# Generated by Django 5.1.4 on 2025-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0017_remove_archivioreferti_alcol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='attivita_sedentaria',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='sport',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
