# Generated by Django 5.1.4 on 2025-05-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0017_visite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visite',
        ),
    ]
