# Generated by Django 5.1.4 on 2025-05-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0018_appointment_paziente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paziente',
        ),
    ]
