# Generated by Django 5.1.4 on 2025-01-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0018_alter_tabellapazienti_attivita_sedentaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='O3_index',
            new_name='a_linoleic_acid',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='aa_epa_quotient',
            new_name='a_photo_m',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='creatinine',
            new_name='a_photo_w',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='fa_saturated',
            new_name='ar_acid',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='ferritin',
            new_name='arachidonic_acid',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='glucose_ex',
            new_name='beenic_acid',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='hct',
            new_name='beta_es_m',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='hdl_chol',
            new_name='beta_es_w',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='hgb',
            new_name='cistatine_c',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='homocysteine',
            new_name='creatinine_m',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='o3fatty_acids',
            new_name='creatinine_w',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='o6fatty_acids',
            new_name='d_dimero',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='o6o3_fatty_acids_quotient',
            new_name='dhea_m',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='o9o7fatty_acids',
            new_name='dhea_w',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='rbc',
            new_name='dih_gamma_lin_acid',
        ),
        migrations.RenameField(
            model_name='datiestesireferti',
            old_name='s_u_fatty_acids',
            new_name='doco_acid',
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='eico_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ferritin_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ferritin_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ft3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ft4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gamma_lin_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='got_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='got_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gpt_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='gpt_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hct_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hct_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hdl_chol_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hdl_chol_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hgb_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='hgb_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='indicano',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='inter_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='inter_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='lin_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='my_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ner_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='nt_pro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ol_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='p_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='pai_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='pal_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='prog_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='prog_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='rbc_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='rbc_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='sa_un_fatty_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='scatolo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='shbg_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='shbg_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='st_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='telotest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='testo_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='testo_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tnf_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tsh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='uricemy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='uricemy_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='v_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='v_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='ves2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
