# Generated by Django 5.1.4 on 2025-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0018_delete_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='utentiregistraticredenziali',
            name='isSecretary',
            field=models.BooleanField(default=False),
        ),
    ]
