# Generated by Django 5.1.4 on 2025-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0019_rename_o3_index_datiestesireferti_a_linoleic_acid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivioreferti',
            name='data_ora_creazione',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
