# Generated by Django 5.1.4 on 2025-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0019_remove_appointment_paziente'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_cerebrale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_cuore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_epatica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_m_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_ormonale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_renale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_s_i',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='salute_sangue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
