# Generated by Django 5.1.4 on 2025-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0020_datiestesirefertietabiologica_salute_cerebrale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiestesirefertietabiologica',
            name='sideremia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
