# Generated by Django 5.1.4 on 2025-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0020_archivioreferti_data_ora_creazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiestesireferti',
            name='aa_epa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='o3_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='o3o6_fatty_acid_quotient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
