# Generated by Django 5.1.4 on 2025-05-16 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0021_datiestesirefertietabiologica_sideremia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobiotaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='microbiota_reports/%Y/%m/%d/')),
                ('dati_estratti', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caricato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microbiota_reports', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
