# Generated by Django 5.1.4 on 2025-05-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0019_utentiregistraticredenziali_issecretary'),
        ('BioVitalAge', '0022_microbiotareport'),
    ]

    operations = [
    ]
