# Generated by Django 5.1.4 on 2025-01-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0022_rename_a_photo_datiestesireferti_g_gt_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiestesireferti',
            name='direct_bili',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='indirect_bili',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesireferti',
            name='tot_bili',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
