# Generated by Django 5.1.5 on 2025-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0023_datiestesireferti_direct_bili_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
