# Generated by Django 5.1.4 on 2025-05-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0024_visite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visite',
        ),
    ]
