# Generated by Django 5.1.5 on 2025-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0024_tabellapazienti_email_tabellapazienti_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
