# Generated by Django 5.1.5 on 2025-05-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0025_delete_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paziente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appuntamenti', to='BioVitalAge.tabellapazienti'),
        ),
    ]
