# Generated by Django 5.1.4 on 2025-05-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0026_appointment_paziente'),
        ('BioVitalAge', '0026_remove_microbiotareport_dati_estratti_and_more'),
    ]

    operations = [
    ]
