# Generated by Django 5.1.5 on 2025-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0026_tabellapazienti_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='associate_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='lastVisit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='upcomingVisit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
