# Generated by Django 5.2.1 on 2025-05-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0026_appointment_paziente'),
        ('BioVitalAge', '0027_rename_abbondanza_relativa_generale_microbiotareport_ac_biliari_and_more'),
    ]

    operations = [
    ]
