# Generated by Django 5.1.4 on 2025-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0027_merge_20250527_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refertietametabolica',
            old_name='ogtt',
            new_name='ogtt1',
        ),
        migrations.AddField(
            model_name='refertietametabolica',
            name='ogtt2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
