# Generated by Django 5.1.4 on 2025-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0028_archiviorefertitest_datiestesirefertitest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='rh_factor',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
