# Generated by Django 5.1.4 on 2025-01-31 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0028_archiviorefertitest_datiestesirefertitest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescrizioniUtenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codicePrescrizione', models.IntegerField(blank=True, null=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrescrizioniEsami', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
