# Generated by Django 5.1.4 on 2025-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0028_rename_ogtt_refertietametabolica_ogtt1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refertietametabolica',
            old_name='bili_t',
            new_name='bili_d',
        ),
        migrations.AddField(
            model_name='refertietametabolica',
            name='bili_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
