# Generated by Django 5.1.4 on 2025-01-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0029_prescrizioniutenti'),
        ('BioVitalAge', '0029_tabellapazienti_rh_factor'),
    ]

    operations = [
    ]
