# Generated by Django 5.1.4 on 2025-02-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0030_merge_20250131_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datiestesireferti',
            name='b_2_spike',
        ),
        migrations.RemoveField(
            model_name='datiestesireferti',
            name='b_2_spike_m1',
        ),
        migrations.RemoveField(
            model_name='datiestesireferti',
            name='cm',
        ),
    ]
