# Generated by Django 5.1.5 on 2025-02-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0031_remove_datiestesireferti_b_2_spike_and_more'),
        ('BioVitalAge', '0031_tabellapazienti_heart_rate_tabellapazienti_pressure'),
    ]

    operations = [
    ]
