# Generated by Django 5.1.5 on 2025-02-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0032_merge_20250206_1226'),
        ('BioVitalAge', '0032_merge_20250206_1401'),
    ]

    operations = [
    ]
