# Generated by Django 5.1.4 on 2025-02-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0033_elencovisitepaziente_esamevisita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esamevisita',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='esamevisita',
            name='metodica',
        ),
    ]
