# Generated by Django 5.1.4 on 2025-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0034_remove_esamevisita_descrizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elencovisitepaziente',
            name='data_visita',
            field=models.DateField(auto_now_add=True),
        ),
    ]
