# Generated by Django 5.1.5 on 2025-02-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0033_merge_20250207_0859'),
        ('BioVitalAge', '0035_alter_elencovisitepaziente_data_visita'),
    ]

    operations = [
    ]
