# Generated by Django 5.1.5 on 2025-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0036_merge_20250210_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='acqua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='bmr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='eta_metabolica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='grasso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='grasso_viscerale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='massa_muscolare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='massa_ossea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='whr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='whtr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
