# Generated by Django 5.1.4 on 2025-02-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0036_merge_20250210_1538'),
        ('BioVitalAge', '0038_tabellapazienti_punteggio_fisico'),
    ]

    operations = [
    ]
