# Generated by Django 5.1.4 on 2025-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0038_tabellapazienti_punteggio_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='alcol',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
