# Generated by Django 5.1.4 on 2025-02-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0039_alter_tabellapazienti_alcol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='alcol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='alcol_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='alcol_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
