# Generated by Django 5.1.4 on 2025-02-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0039_merge_20250211_0948'),
        ('BioVitalAge', '0042_alter_tabellapazienti_smoke'),
    ]

    operations = [
    ]
