# Generated by Django 5.1.4 on 2025-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0043_merge_20250211_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabellapazienti',
            old_name='pressure',
            new_name='pressure_max',
        ),
        migrations.AddField(
            model_name='tabellapazienti',
            name='pressure_min',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
