# Generated by Django 5.1.4 on 2025-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0044_rename_pressure_tabellapazienti_pressure_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='storico_punteggi',
            field=models.JSONField(default=list),
        ),
    ]
