# Generated by Django 5.1.5 on 2025-02-19 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0045_tabellapazienti_storico_punteggi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome_paziente', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_paziente', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.IntegerField(blank=True, null=True)),
                ('tipologia_visita', models.CharField(blank=True, choices=[('Generale', 'Generale'), ('Specialistica', 'Specialistica')], max_length=100, null=True)),
                ('diagnosi', models.TextField(blank=True, null=True)),
                ('orario', models.TimeField()),
                ('numero_stanza', models.IntegerField(blank=True, null=True)),
                ('confermato', models.BooleanField(default=False)),
                ('dottore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
