# Generated by Django 5.1.4 on 2025-02-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0045_tabellapazienti_storico_punteggi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datiestesirefertitest',
            old_name='SiIm',
            new_name='MMSE',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='CirPolp',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='Fss',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='WH_ratio',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='WHip_ratio',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='hgs_test',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='sarc_f',
        ),
        migrations.RemoveField(
            model_name='datiestesirefertitest',
            name='sppb',
        ),
    ]
