# Generated by Django 5.1.4 on 2025-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0046_rename_siim_datiestesirefertitest_mmse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='BMI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='CDP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='CST',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='FSS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='GDS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='GS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='HGS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='ISQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='LOC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='PFT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='PPT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='SARC_F',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='Udito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='Vista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='WHR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datiestesirefertitest',
            name='WHR_Ratio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
