# Generated by Django 5.1.4 on 2025-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0048_alter_datiestesirefertitest_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='tabellapazienti',
            constraint=models.UniqueConstraint(fields=('dottore', 'codice_fiscale'), name='unique_paziente_per_dottore'),
        ),
    ]
