# Generated by Django 5.1.4 on 2025-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0049_alter_tabellapazienti_codice_fiscale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utentiregistraticredenziali',
            name='cookie',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
