# Generated by Django 5.1.4 on 2025-02-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0046_appointment'),
        ('BioVitalAge', '0049_alter_tabellapazienti_codice_fiscale_and_more'),
    ]

    operations = [
    ]
