# Generated by Django 5.1.4 on 2025-02-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0050_merge_20250224_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosi',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='eta',
        ),
    ]
