# Generated by Django 5.1.4 on 2025-02-24 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0051_remove_appointment_diagnosi_remove_appointment_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
