# Generated by Django 5.1.4 on 2025-02-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0052_appointment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='numero_stanza',
            new_name='numero_studio',
        ),
    ]
