# Generated by Django 5.1.4 on 2025-03-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0050_utentiregistraticredenziali_cookie'),
        ('BioVitalAge', '0053_rename_numero_stanza_appointment_numero_studio'),
    ]

    operations = [
    ]
