# Generated by Django 5.1.4 on 2025-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0054_merge_20250303_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='giorno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
