# Generated by Django 5.1.4 on 2025-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0055_appointment_giorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tipologia_visita',
            field=models.CharField(blank=True, choices=[('Appuntamento paziente', 'Appuntamento paziente'), ('Appuntamento Società', 'Appuntamento Società'), ('Appuntamento di gruppo', 'Appuntamento di gruppo')], max_length=100, null=True),
        ),
    ]
