# Generated by Django 5.1.4 on 2025-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0056_alter_appointment_tipologia_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='numero_studio',
            field=models.CharField(blank=True, choices=[('Studio 1', 'Studio 1'), ('Studio 2', 'Studio 2'), ('Studio 3', 'Studio 3')], max_length=100, null=True),
        ),
    ]
