# Generated by Django 5.1.4 on 2025-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0058_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='durata',
            field=models.CharField(blank=True, choices=[('30 minuti', '30 minuti'), ('1 ora', '1 ora'), ('2 ore', '2 ore')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='voce_prezzario',
            field=models.CharField(blank=True, choices=[('Voce 1', 'Voce 1'), ('Voce 2', 'Voce 2'), ('Voce 3', 'Voce 3')], max_length=255, null=True),
        ),
    ]
