# Generated by Django 5.1.4 on 2025-03-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0056_tabellapazienti_residence'),
        ('BioVitalAge', '0059_appointment_durata_appointment_voce_prezzario'),
    ]

    operations = [
    ]
