# Generated by Django 5.1.4 on 2025-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0060_merge_20250312_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tipologia_visita',
            field=models.CharField(blank=True, choices=[('Fisioterapia Sportiva', 'Fisioterapia Sportiva'), ('Fisioterapia e Riabilitazione', 'Fisioterapia e Riabilitazione'), ('Fisioestetica', 'Fisioestetica')], max_length=100, null=True),
        ),
    ]
