# Generated by Django 5.1.4 on 2025-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0061_tabellapazienti_a_genarale_tabellapazienti_aborto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='a_genarale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='aborto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='allergie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='ciclo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='costituzione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='d_gastrointestinali',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='diabete_m',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='eloquio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='epilessia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='esordio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='ipertensione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_autoimmune',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_cardiache',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_endocrina',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_metabolica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_neurologica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_polmonari',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_psichiatriche',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_renale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='m_tiroidee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='menarca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='obesita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='p_cardiovascolari',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='p_epatici',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='p_p_altro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='p_respiratori_cronici',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='parto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='patologie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='pensionato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='post_parto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='professione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='psiche',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='r_ambiente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='s_emotivo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='s_nutrizionale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='sintomi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='statura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='t_dosaggio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='t_durata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='t_farmaco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='tumori',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
