# Generated by Django 5.1.4 on 2025-03-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0062_alter_appointment_durata_and_more'),
        ('BioVitalAge', '0062_alter_tabellapazienti_a_genarale_and_more'),
    ]

    operations = [
    ]
