# Generated by Django 5.1.4 on 2025-03-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0063_merge_20250325_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resilienza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('cortisolo', models.FloatField(blank=True, null=True)),
                ('ros', models.FloatField(blank=True, null=True)),
                ('osi', models.FloatField(blank=True, null=True)),
                ('droms', models.FloatField(blank=True, null=True)),
                ('pcr', models.FloatField(blank=True, null=True)),
                ('nlr', models.FloatField(blank=True, null=True)),
                ('homa', models.FloatField(blank=True, null=True)),
                ('ir', models.FloatField(blank=True, null=True)),
                ('omega_3', models.FloatField(blank=True, null=True)),
                ('vo2max', models.FloatField(blank=True, null=True)),
                ('risultato', models.FloatField(blank=True, null=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resilienza', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
