# Generated by Django 5.1.4 on 2025-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0065_valutazionems'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
