# Generated by Django 5.1.4 on 2025-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0066_tabellapazienti_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='alcol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='smoke',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
