# Generated by Django 5.1.4 on 2025-04-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0066_tabellapazienti_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dottore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BioVitalAge.utentiregistraticredenziali'),
        ),
    ]
