# Generated by Django 5.1.4 on 2025-04-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0067_alter_appointment_dottore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='grasso',
        ),
    ]
