# Generated by Django 5.1.4 on 2025-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0068_alter_tabellapazienti_a_genarale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='girth_value',
            field=models.FloatField(blank=True, help_text='Girth value in cm', null=True),
        ),
    ]
