# Generated by Django 5.1.4 on 2025-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0068_remove_tabellapazienti_grasso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellapazienti',
            name='grasso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
