# Generated by Django 5.1.4 on 2025-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0070_tabellapazienti_alt_tabellapazienti_ast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='bmi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
