# Generated by Django 5.1.4 on 2025-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0071_alter_tabellapazienti_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellapazienti',
            name='girth_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabellapazienti',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
