# Generated by Django 5.1.4 on 2025-04-01 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0072_alter_tabellapazienti_girth_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='acqua',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='bili_t',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='bmi_detection_date',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='bmr',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='c_plasmatico',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='c_tot',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='curva_i',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='emoglobina_g',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='eta_metabolica',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='ggt',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='girth_date',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='girth_notes',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='girth_value',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='glicemia',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='grasso',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='grasso_viscerale',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='hdl',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='hgs',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='homa_ir',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='insulina_d',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='ldl',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='massa_muscolare',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='massa_ossea',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='ogtt',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='pcr',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='punteggio_fisico',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='sii',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='storico_punteggi',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='trigliceridi',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='tyg',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='whr',
        ),
        migrations.RemoveField(
            model_name='tabellapazienti',
            name='whtr',
        ),
        migrations.CreateModel(
            name='RefertiEtaMetabolica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referto', models.DateTimeField(default=django.utils.timezone.now)),
                ('bmi', models.CharField(blank=True, max_length=100, null=True)),
                ('grasso', models.CharField(blank=True, max_length=100, null=True)),
                ('acqua', models.CharField(blank=True, max_length=100, null=True)),
                ('massa_muscolare', models.CharField(blank=True, max_length=100, null=True)),
                ('bmr', models.CharField(blank=True, max_length=100, null=True)),
                ('whr', models.CharField(blank=True, max_length=100, null=True)),
                ('whtr', models.CharField(blank=True, max_length=100, null=True)),
                ('glicemia', models.CharField(blank=True, max_length=100, null=True)),
                ('ogtt', models.CharField(blank=True, max_length=100, null=True)),
                ('emoglobina_g', models.CharField(blank=True, max_length=100, null=True)),
                ('insulina_d', models.CharField(blank=True, max_length=100, null=True)),
                ('curva_i', models.CharField(blank=True, max_length=100, null=True)),
                ('homa_ir', models.CharField(blank=True, max_length=100, null=True)),
                ('tyg', models.CharField(blank=True, max_length=100, null=True)),
                ('c_tot', models.CharField(blank=True, max_length=100, null=True)),
                ('hdl', models.CharField(blank=True, max_length=100, null=True)),
                ('ldl', models.CharField(blank=True, max_length=100, null=True)),
                ('trigliceridi', models.CharField(blank=True, max_length=100, null=True)),
                ('ast', models.CharField(blank=True, max_length=100, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('ggt', models.CharField(blank=True, max_length=100, null=True)),
                ('bili_t', models.CharField(blank=True, max_length=100, null=True)),
                ('pcr', models.CharField(blank=True, max_length=100, null=True)),
                ('hgs', models.CharField(blank=True, max_length=100, null=True)),
                ('sii', models.CharField(blank=True, max_length=100, null=True)),
                ('c_plasmatico', models.CharField(blank=True, max_length=100, null=True)),
                ('massa_ossea', models.CharField(blank=True, max_length=100, null=True)),
                ('eta_metabolica', models.CharField(blank=True, max_length=100, null=True)),
                ('grasso_viscerale', models.CharField(blank=True, max_length=100, null=True)),
                ('punteggio_fisico', models.CharField(blank=True, max_length=100, null=True)),
                ('storico_punteggi', models.JSONField(blank=True, default=list)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('bmi_detection_date', models.DateField(blank=True, null=True)),
                ('girth_value', models.CharField(blank=True, max_length=255, null=True)),
                ('girth_notes', models.TextField(blank=True, null=True)),
                ('girth_date', models.DateField(blank=True, null=True)),
                ('dottore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referti_eta_metabolica', to='BioVitalAge.utentiregistraticredenziali')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referti_eta_metabolica', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
