# Generated by Django 5.1.4 on 2025-04-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0073_remove_tabellapazienti_acqua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refertietametabolica',
            old_name='punteggio_fisico',
            new_name='p_fisico',
        ),
    ]
