# Generated by Django 5.1.4 on 2025-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0074_rename_punteggio_fisico_refertietametabolica_p_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='refertietametabolica',
            name='punteggio_finale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
